-- B2.1 — Créer les types ENUM
CREATE TYPE role_utilisateur AS ENUM ('ADMIN', 'GESTIONNAIRE');
CREATE TYPE type_transaction AS ENUM ('VENTE_TEXTILE', 'MOMO_DEPOT', 'MOMO_RETRAIT', 'COMMISSION_MOMO');
CREATE TYPE type_caisse AS ENUM ('STOCK', 'SALAIRE', 'REMBOURSEMENT', 'RESERVE', 'FONDS_ROULEMENT_MOMO');
CREATE TYPE statut_caisse AS ENUM ('NORMAL', 'ALERTE', 'CRITIQUE');
CREATE TYPE action_audit AS ENUM (
  'MODIFICATION_VARIABLE',
  'CREATION_COMPTE',
  'DESACTIVATION_COMPTE',
  'ACTIVATION_COMPTE',
  'CORRECTION_TRANSACTION'
);
